### PR TITLE
Fixed ss method for JSMethodCall

### PR DESCRIPTION
**Pull request by adrianherrera**

### CODE REVIEW

**Comment by erikd** [comment]
Will this fix may actually be correct, it causes all the tests to fail, so the expected test results also need to be adjusted.

**Comment by adrianherrera** [comment]
Ahhh good point, thanks for that! I'll fix that too.

**Comment by adrianherrera** [comment]
Hi Erik,

I fixed the tests too!

Regards,
Adrian

**Comment by erikd** [comment]
Thanks. Patch applied and new version uploaded to Hackage.

**Pull request closed without merging**
